import jsPDF from 'jspdf';

interface LessonPlanPDFOptions {
  plan: string;
  topic: string;
  subject?: string;
  grade?: string;
}

/**
 * Exports a generated lesson plan to a nicely formatted PDF.
 */
export function exportLessonPlanToPDF({ plan, topic, subject, grade }: LessonPlanPDFOptions): void {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const marginLeft = 20;
  const marginRight = 20;
  const marginTop = 25;
  const marginBottom = 25;
  const contentWidth = pageWidth - marginLeft - marginRight;

  let cursorY = marginTop;

  // ── Helpers ──────────────────────────────────────────────

  const addPageIfNeeded = (spaceNeeded: number) => {
    if (cursorY + spaceNeeded > pageHeight - marginBottom) {
      doc.addPage();
      cursorY = marginTop;
      addFooter(doc.getNumberOfPages());
    }
  };

  const addFooter = (pageNum: number) => {
    const footerY = pageHeight - 12;
    doc.setFontSize(8);
    doc.setTextColor(160, 160, 160);
    doc.text('Generated by Silid Classroom — AI Lesson Plan Generator', marginLeft, footerY);
    doc.text(`Page ${pageNum}`, pageWidth - marginRight, footerY, { align: 'right' });
  };

  // ── Header ───────────────────────────────────────────────

  // Coral accent bar at the top
  doc.setFillColor(192, 57, 43); // #C0392B
  doc.rect(0, 0, pageWidth, 8, 'F');

  // Title
  cursorY = 20;
  doc.setFontSize(22);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(33, 33, 33);
  doc.text('Lesson Plan', marginLeft, cursorY);
  cursorY += 10;

  // Topic
  doc.setFontSize(16);
  doc.setTextColor(192, 57, 43);
  doc.text(topic, marginLeft, cursorY);
  cursorY += 8;

  // Subject & Grade metadata line
  if (subject || grade) {
    doc.setFontSize(10);
    doc.setTextColor(120, 120, 120);
    const meta = [subject, grade].filter(Boolean).join('  •  ');
    doc.text(meta, marginLeft, cursorY);
    cursorY += 6;
  }

  // Divider line
  cursorY += 2;
  doc.setDrawColor(220, 220, 220);
  doc.setLineWidth(0.5);
  doc.line(marginLeft, cursorY, pageWidth - marginRight, cursorY);
  cursorY += 8;

  // ── Body ─────────────────────────────────────────────────

  const lines = plan.split('\n');

  for (const line of lines) {
    const trimmed = line.trim();

    // Skip empty lines — just add a small gap
    if (!trimmed) {
      cursorY += 4;
      continue;
    }

    // Detect section headers (ALL CAPS lines, at least 3 chars)
    const isHeader = trimmed.length >= 3 && trimmed === trimmed.toUpperCase() && /[A-Z]/.test(trimmed);

    if (isHeader) {
      addPageIfNeeded(16);
      cursorY += 4;

      // Teal accent bar for section headers
      doc.setFillColor(27, 108, 168); // #1B6CA8
      doc.rect(marginLeft, cursorY - 4.5, 3, 6, 'F');

      doc.setFontSize(12);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(27, 108, 168);
      doc.text(trimmed, marginLeft + 6, cursorY);
      cursorY += 8;
    } else {
      // Regular body text — wrap it
      doc.setFontSize(10);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(55, 55, 55);

      const wrappedLines = doc.splitTextToSize(trimmed, contentWidth);
      const blockHeight = wrappedLines.length * 5;

      addPageIfNeeded(blockHeight);
      doc.text(wrappedLines, marginLeft, cursorY);
      cursorY += blockHeight + 2;
    }
  }

  // ── Footer on all pages ──────────────────────────────────

  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    addFooter(i);
  }

  // ── Save ─────────────────────────────────────────────────

  const safeFilename = topic.replace(/[^a-zA-Z0-9 ]/g, '').replace(/\s+/g, '_').substring(0, 50);
  doc.save(`Lesson_Plan_${safeFilename}.pdf`);
}
